### ISSUE TITLE
Changing Online Status

### ISSUE THREAD

**Issue by JGriffin34432** [MacDue/BanUtil#2]
How do I change to online status on the bot?

![68747470733a2f2f63646e2e7261776769742e636f6d2f5a657274686f782f4d696e692d446973636f72642d5468656d65732f6d61737465722f73637265656e73686f74732f686964656368616e6e656c73322e706e67](https://user-images.githubusercontent.com/32964555/35926870-404b5ae6-0bf7-11e8-8d56-5ef61b905ad5.png)

**Comment by MacDue** [comment]
https://jitpack.io/com/github/austinv11/Discord4j/2.9.3/javadoc/

The client has a bunch of methods like `.dnd()` or `.streaming()`. Read the docs and make your own changes.
