### ISSUE TITLE
what should i put in the owner_id?

### ISSUE THREAD

**Issue by 60zs** [MacDue/BanUtil#3]
i have tried putting in the owner role id and the id of the owner of the server and im still getting the error about owner id
pls help

**Comment by MacDue** [comment]
99.99999999% chance you're not putting the owner/role id & instead putting the name.
You get the id by enabling "developer mode" and right-clicking on the role/user and do "copy ID". 
Other than that, I can't help you. This is 4-year-old software I've forgotten all about.
